openapi: 3.0.0
tags: []
info:
  title: Fleet
  description: OpenAPI schema for Fleet API endpoints
  version: '0.2'
  contact:
    name: Fleet Team
  license:
    name: Elastic License 2.0
    url: https://www.elastic.co/licensing/elastic-license
servers:
  - url: http://localhost:5601/api/fleet
    description: local
paths:
  /agent_policies:
    post:
      summary: Agent policy - Create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/agent_policy'
      operationId: create-agent-policy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_agent_policy'
  /agent_policies/{agentPolicyId}:
    parameters:
      - schema:
          type: string
        name: agentPolicyId
        in: path
        required: true
    get:
      summary: Agent policy - Info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/agent_policy'
                required:
                  - item
      operationId: agent-policy-info
      description: Get one agent policy
    put:
      summary: Agent policy - Update
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/agent_policy'
                required:
                  - item
      operationId: update-agent-policy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_agent_policy'
  /agent_policies/delete:
    post:
      summary: Agent policy - Delete
      operationId: delete-agent-policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  success:
                    type: boolean
                required:
                  - id
                  - success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                agentPolicyId:
                  type: string
              required:
                - agentPolicyId
  /package_policies/_bulk_get:
    post:
      summary: Package policies - Bulk Get
      tags: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: list of package policy ids
                ignoreMissing:
                  type: boolean
              required:
                - ids
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/package_policy'
                required:
                  - items
      operationId: bulk-get-package-policies
  /package_policies:
    post:
      summary: Package policy - Create
      operationId: create-package-policy
      requestBody:
        description: >-
          You should use inputs as an object and not use the deprecated inputs
          array.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/package_policy_request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/package_policy'
                required:
                  - item
  /package_policies/delete:
    post:
      summary: Package policy - Delete
      operationId: post-delete-package-policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                packagePolicyIds:
                  type: array
                  items:
                    type: string
                force:
                  type: boolean
              required:
                - packagePolicyIds
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    success:
                      type: boolean
                    # Missing package and policy_id.
                  required:
                    - id
                    - success
  /enrollment_api_keys:
    post:
      summary: Enrollment API Key - Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of enrollment API key.
                policy_id:
                  type: string
                  description: Agent policy to assign to enrolled Agents using this key.
              required:
                - name
                - policy_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/enrollment_api_key'
                  action:
                    type: string
#                    enum:
#                      - created
      operationId: create-enrollment-api-keys
  /enrollment_api_keys/{keyId}:
    parameters:
      - schema:
          type: string
        name: keyId
        in: path
        required: true
    get:
      summary: Enrollment API Key - Info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  item:
                    $ref: '#/components/schemas/enrollment_api_key'
                required:
                  - item
      operationId: get-enrollment-api-key
    delete:
      summary: Enrollment API Key - Delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
#                    enum:
#                      - deleted
                required:
                  - action
      operationId: delete-enrollment-api-key
components:
  schemas:
    new_package_policy:
      title: New package policy
      type: object
      description: ''
      properties:
        enabled:
          type: boolean
        package:
          type: object
          properties:
            name:
              type: string
            version:
              type: string
            title:
              type: string
          required:
            - name
            - version
        namespace:
          type: string
        output_id:
          type: string
          deprecated: true
        inputs:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              enabled:
                type: boolean
              processors:
                type: array
                items:
                  type: string
              streams:
                type: array
                items: { }
              config:
                type: object
              vars:
                type: object
            required:
              - type
              - enabled
        policy_id:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - inputs
        - name
    package_policy:
      title: Package policy
      allOf:
        - type: object
          properties:
            id:
              type: string
            revision:
              type: number
            inputs:
              type: array
              items: { }
          required:
            - id
            - revision
        - $ref: '#/components/schemas/new_package_policy'
    agent_policy:
      allOf:
        - $ref: '#/components/schemas/new_agent_policy'
        - type: object
          properties:
            id:
              type: string
            status:
              type: string
              enum:
                - active
                - inactive
            package_policies:
              description: >-
                This field is present only when retrieving a single agent
                policy, or when retrieving a list of agent policy with the
                ?full=true parameter
              type: array
              items:
                $ref: '#/components/schemas/package_policy'
            updated_on:
              type: string
              format: date-time
            updated_by:
              type: string
            data_output_id:
              type: string
              nullable: true
            monitoring_output_id:
              type: string
              nullable: true
            fleet_server_host_id:
              type: string
              nullable: true
            download_source_id:
              type: string
              nullable: true
            revision:
              type: number
            agents:
              type: number
          required:
            - id
            - status
    new_agent_policy:
      title: New agent policy
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        namespace:
          type: string
        description:
          type: string
        monitoring_enabled:
          type: array
          items:
            type: string
            enum:
              - metrics
              - logs
        data_output_id:
          type: string
          nullable: true
        monitoring_output_id:
          type: string
          nullable: true
        fleet_server_host_id:
          type: string
          nullable: true
        download_source_id:
          type: string
          nullable: true
        unenroll_timeout:
          type: number
        inactivity_timeout:
          type: number
      required:
        - name
        - namespace
    enrollment_api_key:
      title: Enrollment API key
      type: object
      properties:
        id:
          type: string
        api_key_id:
          type: string
        api_key:
          type: string
        name:
          type: string
        active:
          type: boolean
        policy_id:
          type: string
        created_at:
          type: string
      required:
        - id
        - api_key_id
        - api_key
        - active
        - created_at
    package_policy_request:
      title: Package Policy Request
      type: object
      properties:
        id:
          type: string
          description: Package policy unique identifier
        name:
          type: string
          description: Package policy name (should be unique)
          example: nginx-123
        description:
          type: string
          description: Package policy description
          example: my description
        namespace:
          type: string
          description: namespace by default "default"
          example: default
        policy_id:
          type: string
          description: Agent policy ID where that package policy will be added
          example: agent-policy-id
        package:
          type: object
          properties:
            name:
              type: string
              description: Package name
              example: nginx
            version:
              type: string
              description: Package version
              example: 1.6.0
          required:
            - name
            - version
        vars:
          type: object
          description: >-
            Package root level variable (see integration documentation for more
            information)
        inputs:
          type: object
          description: >-
            Package policy inputs (see integration documentation to know what
            inputs are available)
          example:
            nginx-logfile:
              enabled: true
              streams:
                nginx.access:
                  enabled: true
                  vars:
                    paths:
                      - /var/log/nginx/access.log*
                    tags:
                      - nginx-access
                    preserve_original_event: false
                    ignore_older: 72h
          additionalProperties:
            $ref: '#/components/schemas/package_policy_input_simplified'
        force:
          type: boolean
          description: >-
            Force package policy creation even if package is not verified, or if
            the agent policy is managed.
      required:
        - name
        - policy_id
        - package
    package_policy_input_simplified:
      properties:
        enabled:
          type: boolean
          description: enable or disable that input, (default to true)
        vars:
          type: object
          description: >-
            Input level variable (see integration documentation for more
            information)
        streams:
          type: object
          description: >-
            Input streams (see integration documentation to know what
            streams are available)
          additionalProperties:
            $ref: '#/components/schemas/package_policy_stream_simplified'
    package_policy_stream_simplified:
      properties:
        enabled:
          type: boolean
          description: enable or disable that stream, (default to true)
        vars:
          type: object
          description: >-
            Stream level variable (see integration documentation for
            more information)
